version: '2'
services:
    angular5app-app:
        image: angular5app
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://angular5app-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angular5app-mssql:
        extends:
            file: mssql.yml
            service: angular5app-mssql
